#!/bin/bash
# yes, Inkscape is this crazy - if DISPLAY is not set, it waits
# for MIT-MAGIC-COOKIE until timeout (30 seconds ?) before
# continuing... :D
export DISPLAY=:0

ICON_IDS=`cat icons.svg | grep -o -E 'icon_[0-9A-Za-z_]*'`

HEIGHT=88
EXTENSION="png"
if [ $1 ];then EXTENSION=$1;fi

echo ${ICON_IDS}

rm -rf icons/*

echo "== generating normal icons =="

#inkscape --without-gui --export-plain-svg -f icons.svg -i $i -e icons/${b}.${EXTENSION} -h ${HEIGHT}
parallel bash generate_icon.sh ${HEIGHT} ${EXTENSION} ::: ${ICON_IDS}

# remove the mysterious -force file generated by Inkscape
rm -f "-force"

echo "== normal icon generated =="
